resource "datadog_dashboard_json" "pipeline_d1" {
  dashboard = jsonencode({
    title       = "Exchange - Control-M Pipeline D+1"
    description = "Control-M simulator execution metrics emitted through DogStatsD/APM intake: executions, status, duration, retries, SLA, and DQ checks."
    layout_type = "ordered"
    tags        = ["env:demo", "team:data-platform", "domain:capital-markets", "orchestrator:controlm"]

    template_variables = [
      {
        name    = "env"
        prefix  = "env"
        default = "demo"
      },
      {
        name    = "ctm_job"
        prefix  = "ctm_job"
        default = "*"
      }
    ]

    widgets = [
      {
        definition = {
          title       = "Control-M Execution KPIs"
          type        = "group"
          layout_type = "ordered"
          widgets = [
            {
              definition = {
                title = "Job Executions"
                type  = "query_value"
                requests = [{
                  q          = "sum:controlm.job.executions{env:$env,ctm_job:$ctm_job}.as_count()"
                  aggregator = "sum"
                }]
                autoscale = true
                precision = 0
              }
            },
            {
              definition = {
                title = "Ended OK"
                type  = "query_value"
                requests = [{
                  q          = "sum:controlm.job.ended_ok.count{env:$env,ctm_job:$ctm_job}.as_count()"
                  aggregator = "sum"
                }]
                autoscale = true
                precision = 0
              }
            },
            {
              definition = {
                title = "Ended NOT OK"
                type  = "query_value"
                requests = [{
                  q          = "sum:controlm.job.ended_not_ok.count{env:$env,ctm_job:$ctm_job}.as_count()"
                  aggregator = "sum"
                }]
                autoscale = true
                precision = 0
              }
            },
            {
              definition = {
                title = "SLA Violations"
                type  = "query_value"
                requests = [{
                  q          = "sum:controlm.job.sla.violation.count{env:$env,ctm_job:$ctm_job}.as_count()"
                  aggregator = "sum"
                }]
                autoscale = true
                precision = 0
              }
            }
          ]
        }
      },
      {
        definition = {
          title = "Duration by Control-M Job"
          type  = "timeseries"
          requests = [{
            q            = "avg:controlm.job.duration_seconds{env:$env,ctm_job:$ctm_job} by {ctm_job}"
            display_type = "line"
          }]
          yaxis = {
            scale = "linear"
            label = "seconds"
          }
        }
      },
      {
        definition = {
          title = "Rows Produced by Job"
          type  = "timeseries"
          requests = [{
            q            = "avg:controlm.job.output_rows{env:$env,ctm_job:$ctm_job} by {ctm_job}"
            display_type = "bars"
          }]
        }
      },
      {
        definition = {
          title = "Retries by Job"
          type  = "toplist"
          requests = [{
            q = "max:controlm.job.retries{env:$env,ctm_job:$ctm_job} by {ctm_job}"
          }]
        }
      },
      {
        definition = {
          title = "DQ Checks Failed"
          type  = "query_value"
          requests = [{
            q          = "sum:controlm.dq.checks_failed.count{env:$env}.as_count()"
            aggregator = "sum"
          }]
          autoscale = true
          precision = 0
        }
      },
      {
        definition = {
          title            = "Dashboard Query Notes"
          type             = "note"
          content          = <<-EOT
## Control-M metric queries

Primary custom metric:
`sum:controlm.job.executions{env:demo,ctm_job:leitura_dados}.as_count()`

APM trace metric generated by the smoke sample:
`sum:trace.controlm.job.leitura_dados.hits{env:demo}`

Real pipeline span metrics use the actual job names:
`trace.controlm.job.close_market_eod.hits`,
`trace.controlm.job.reconcile_d1_positions.hits`,
`trace.controlm.job.quality_gate_d1.hits`,
`trace.controlm.job.publish_d1_reports.hits`.
EOT
          background_color = "white"
          font_size        = "14"
          text_align       = "left"
          show_tick        = false
          tick_edge        = "left"
          tick_pos         = "50%"
        }
      }
    ]
  })
}
