#!/usr/bin/env python3
"""generate.py — reads jobs/manifest.yaml and produces the four Job:Type
variants plus the _job_io_generated.py table consumed by run_job.py.

Run via: `make ctm-generate` (or `python controlm/generate.py`).

DO NOT edit the generated files directly. Edit manifest.yaml and re-run.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write(
        "ERROR: PyYAML is required. Install with: pip install pyyaml\n"
    )
    sys.exit(2)


HERE = Path(__file__).resolve().parent
MANIFEST = HERE / "jobs" / "manifest.yaml"
JOBS_DIR = HERE / "jobs"
SCRIPTS_DIR = HERE / "scripts"
SERVICES_DIR = HERE.parent / "services"


def load_manifest() -> dict:
    with MANIFEST.open() as fh:
        m = yaml.safe_load(fh)
    _validate(m)
    return m


def _validate(m: dict) -> None:
    job_names = {j["name"] for j in m["jobs"]}
    if len(job_names) != len(m["jobs"]):
        raise ValueError("Duplicate job names in manifest.")
    lineage_only = m.get("lineage_only_jobs", [])
    all_lineage_names = [j["name"] for j in [*lineage_only, *m["jobs"]]]
    if len(set(all_lineage_names)) != len(all_lineage_names):
        raise ValueError("Duplicate job names across jobs and lineage_only_jobs.")
    valid_ns = set(m["datasets"].keys())
    for job in m["jobs"]:
        dep = job.get("depends_on")
        if dep is not None and dep not in job_names:
            raise ValueError(
                f"Job '{job['name']}' depends_on '{dep}' which is not defined."
            )
    for job in [*lineage_only, *m["jobs"]]:
        for io_kind in ("inputs", "outputs"):
            for ds in job.get(io_kind, []):
                if ds["ns"] not in valid_ns:
                    raise ValueError(
                        f"Job '{job['name']}' references undeclared namespace "
                        f"'{ds['ns']}'. Declare it under datasets:."
                    )


def _job_key(pipeline_name: str, job_name: str) -> str:
    return f"{pipeline_name.split('_')[0]}_{job_name}"


def _common_job_fields(m: dict, job: dict) -> dict:
    d = m["defaults"]
    fields = {
        "Host": d["ctm_agent_host"],
        "RunAs": d["run_as"],
        "Description": job.get("description", ""),
        "SLA": {"Duration": job["sla"]},
    }
    if job.get("depends_on"):
        fields["DependsOn"] = [
            {
                "Name": _job_key(m["pipeline"]["name"], job["depends_on"]),
                "State": "OK",
            }
        ]
    return fields


def _python_invocation(m: dict, job_name: str) -> str:
    """Build the canonical 'python /scripts/run_job.py --job X --date %%ODATE%%'
    string using the configured variables.
    """
    d = m["defaults"]
    return (
        f'{d["python_bin"]} {d["script_dir"]}{d["path_sep"]}run_job.py '
        f"--job {job_name} --date %%ODATE%%"
    )


# ── Variant 1: Job:Script ───────────────────────────────────────────────────
def build_script_variant(m: dict) -> dict:
    folder: dict = {
        "Type": "SimpleFolder",
        "Comment": (
            "Auto-generated by controlm/generate.py from manifest.yaml. "
            "Variant: Job:Script (file on disk). Deploy: setup.sh --variant script"
        ),
    }
    d = m["defaults"]
    for job in m["jobs"]:
        key = _job_key(m["pipeline"]["name"], job["name"])
        folder[key] = {
            "Type": "Job:Script",
            "FileName": "run_job.py",
            "FilePath": d["script_dir"],
            "Arguments": f'--job {job["name"]} --date %%ODATE%%',
            "Command": _python_invocation(m, job["name"]),
            **_common_job_fields(m, job),
        }
    return {m["pipeline"]["name"]: folder}


# ── Variant 2: Job:Command ──────────────────────────────────────────────────
def build_command_variant(m: dict) -> dict:
    folder: dict = {
        "Type": "SimpleFolder",
        "Comment": (
            "Auto-generated. Variant: Job:Command (inline command, no file on agent). "
            "Deploy: setup.sh --variant command"
        ),
    }
    for job in m["jobs"]:
        key = _job_key(m["pipeline"]["name"], job["name"])
        folder[key] = {
            "Type": "Job:Command",
            "Command": _python_invocation(m, job["name"]),
            **_common_job_fields(m, job),
        }
    return {m["pipeline"]["name"]: folder}


# ── Variant 3: Job:EmbeddedScript ───────────────────────────────────────────
def build_embedded_variant(m: dict) -> dict:
    folder: dict = {
        "Type": "SimpleFolder",
        "Comment": (
            "Auto-generated. Variant: Job:EmbeddedScript (script inline in JSON). "
            "Deploy: setup.sh --variant embedded"
        ),
    }
    d = m["defaults"]
    for job in m["jobs"]:
        key = _job_key(m["pipeline"]["name"], job["name"])
        # Embedded script is POSIX-shell-like with a shebang. Works on Linux and
        # on Windows if the agent runs the script via cmd /c (Control-M handles this).
        script = (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            f'exec {_python_invocation(m, job["name"])}\n'
        )
        folder[key] = {
            "Type": "Job:EmbeddedScript",
            "Script": script,
            "FileName": f'embedded_{job["name"]}.sh',
            **_common_job_fields(m, job),
        }
    return {m["pipeline"]["name"]: folder}


# ── Variant 4: Job:Database ─────────────────────────────────────────────────
def build_database_variant(m: dict) -> dict:
    folder: dict = {
        "Type": "SimpleFolder",
        "Comment": (
            "Auto-generated. Variant: Job:Database (pure SQL, no Python on agent). "
            "Only jobs with a sql: block in the manifest are included. "
            "Deploy: setup.sh --variant database"
        ),
    }
    included = 0
    for job in m["jobs"]:
        sql_block = job.get("sql")
        if not sql_block:
            continue
        included += 1
        key = _job_key(m["pipeline"]["name"], job["name"])
        # Job:Database requires a connection profile created in Control-M.
        # We parameterize via %%DB_CONN_<TYPE>%%. B3 maps it to their real profile.
        conn_var = "%%DB_CONN_ORACLE%%" if sql_block["type"] == "oracle" else "%%DB_CONN_MSSQL%%"
        folder[key] = {
            "Type": "Job:Database",
            "ConnectionProfile": conn_var,
            "SQLScript": sql_block["query"],
            "Autocommit": "Y",
            **_common_job_fields(m, job),
        }
    if included == 0:
        folder["_Note"] = {
            "Type": "SimpleFolder",
            "Comment": "No jobs in manifest have a sql: block; database variant is empty.",
        }
    return {m["pipeline"]["name"]: folder}


# ── Generated JOB_IO table ──────────────────────────────────────────────────
def build_job_io_module(m: dict) -> str:
    """Generates _job_io_generated.py — imported by run_job.py."""
    ns = m["datasets"]
    pipeline_name = m["pipeline"]["name"].lower()
    lines: list[str] = [
        '"""Auto-generated by controlm/generate.py from jobs/manifest.yaml.',
        "DO NOT EDIT — re-run `make ctm-generate` after editing the manifest.",
        '"""',
        "",
        "import os",
        "",
        f'JOB_NAMESPACE = os.environ.get("OL_NAMESPACE", "{m["pipeline"]["namespace"]}")',
        f'PIPELINE_NAME = os.environ.get("OL_PIPELINE", "{pipeline_name}")',
        f'PRODUCER = "{m["pipeline"]["producer"]}"',
        "",
        "# Namespace URIs (from manifest.datasets)",
    ]
    for k, v in ns.items():
        env_name = {
            "oracle": "OL_ORACLE_NS",
            "sqlserver": "OL_SQLSERVER_NS",
            "mysql": "OL_MYSQL_NS",
            "minio": "OL_S3_NS",
        }.get(k, f"OL_{k.upper()}_NS")
        lines.append(f'{k.upper()}_NS = os.environ.get("{env_name}", "{v}")')
    lines.append("")
    lines.append("JOB_IO = {")
    for job in [*m.get("lineage_only_jobs", []), *m["jobs"]]:
        lines.append(f'    "{job["name"]}": {{')
        for io_kind in ("inputs", "outputs"):
            datasets = job.get(io_kind, [])
            if not datasets:
                lines.append(f'        "{io_kind}": [],')
                continue
            lines.append(f'        "{io_kind}": [')
            for ds in datasets:
                lines.append(
                    f'            {{"namespace": {ds["ns"].upper()}_NS, "name": "{ds["name"]}"}},'
                )
            lines.append("        ],")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def write(path: Path, content: str) -> None:
    path.write_text(content)
    rel = path.relative_to(HERE.parent)
    print(f"  wrote {rel}")


def main() -> int:
    print(f"Reading {MANIFEST.relative_to(HERE.parent)}")
    m = load_manifest()
    print(f"  pipeline={m['pipeline']['name']}, jobs={len(m['jobs'])}")
    print()

    print("Generating Control-M JSON variants:")
    variants = {
        "script":   build_script_variant(m),
        "command":  build_command_variant(m),
        "embedded": build_embedded_variant(m),
        "database": build_database_variant(m),
    }
    for name, payload in variants.items():
        out = JOBS_DIR / f"market_d1_{name}.json"
        write(out, json.dumps(payload, indent=2, ensure_ascii=False) + "\n")

    print()
    print("Generating Python JOB_IO table:")
    job_io_module = build_job_io_module(m)
    write(SCRIPTS_DIR / "_job_io_generated.py", job_io_module)
    write(SERVICES_DIR / "controlm-sim" / "lineage_contract.py", job_io_module)
    write(SERVICES_DIR / "pipeline-runner" / "lineage_contract.py", job_io_module)

    print()
    print("Done. Next steps:")
    print("  make ctm-deploy-all          # deploy every variant to Workbench")
    print("  make ctm-test-all-variants   # run each variant sequentially")
    return 0


if __name__ == "__main__":
    sys.exit(main())
