-- Kept intentionally empty.
--
-- Oracle XE 21c executes every *.sql file in this directory on first startup.
-- The active source schema, seed data, and Datadog DBM grants live in
-- 01_create_tables.sql. The previous contents of this file used Oracle 23c
-- CREATE IF NOT EXISTS syntax, which is invalid on the XE 21c image used by
-- docker-compose/podman-compose.
