"""Auto-generated by controlm/generate.py from jobs/manifest.yaml.
DO NOT EDIT — re-run `make ctm-generate` after editing the manifest.
"""

import os

JOB_NAMESPACE = os.environ.get("OL_NAMESPACE", "b3-poc-demo-v3")
PIPELINE_NAME = os.environ.get("OL_PIPELINE", "b3_d1_pipeline")
PRODUCER = "https://github.com/b3-poc/controlm-workbench"

# Namespace URIs (from manifest.datasets)
ORACLE_NS = os.environ.get("OL_ORACLE_NS", "oracle://demo-oracle:1521")
SQLSERVER_NS = os.environ.get("OL_SQLSERVER_NS", "sqlserver://demo-sqlserver:1433")
MYSQL_NS = os.environ.get("OL_MYSQL_NS", "mysql://demo-mysql:3306/exchange")
MINIO_NS = os.environ.get("OL_S3_NS", "s3://mock-exchange")

JOB_IO = {
    "market_data_ingest": {
        "inputs": [],
        "outputs": [
            {"namespace": ORACLE_NS, "name": "XEPDB1.DEMOPOC.ASTADRVT_TRADE_MVMT"},
            {"namespace": ORACLE_NS, "name": "XEPDB1.DEMOPOC.ASTANO_FGBE_DRVT_PSTN"},
            {"namespace": ORACLE_NS, "name": "XEPDB1.DEMOPOC.ASTACASH_MRKT_PSTN"},
        ],
    },
    "close_market_eod": {
        "inputs": [
            {"namespace": ORACLE_NS, "name": "XEPDB1.DEMOPOC.ASTADRVT_TRADE_MVMT"},
        ],
        "outputs": [
            {"namespace": SQLSERVER_NS, "name": "demopoc.dbo.ADWPM_MOVIMENTO_NEGOCIO_DERIVATIVO"},
        ],
    },
    "reconcile_d1_positions": {
        "inputs": [
            {"namespace": ORACLE_NS, "name": "XEPDB1.DEMOPOC.ASTANO_FGBE_DRVT_PSTN"},
            {"namespace": ORACLE_NS, "name": "XEPDB1.DEMOPOC.ASTACASH_MRKT_PSTN"},
        ],
        "outputs": [
            {"namespace": SQLSERVER_NS, "name": "demopoc.dbo.ADWPM_POSICAO_DERIVATIVO_NAO_FUNGIVEL"},
            {"namespace": SQLSERVER_NS, "name": "demopoc.dbo.ADWPM_POSICAO_MERCADO_A_VISTA"},
        ],
    },
    "quality_gate_d1": {
        "inputs": [
            {"namespace": SQLSERVER_NS, "name": "demopoc.dbo.ADWPM_MOVIMENTO_NEGOCIO_DERIVATIVO"},
            {"namespace": SQLSERVER_NS, "name": "demopoc.dbo.ADWPM_POSICAO_DERIVATIVO_NAO_FUNGIVEL"},
            {"namespace": SQLSERVER_NS, "name": "demopoc.dbo.ADWPM_POSICAO_MERCADO_A_VISTA"},
        ],
        "outputs": [
            {"namespace": SQLSERVER_NS, "name": "demopoc.dbo.ADWPM_DQ_RESULTS"},
        ],
    },
    "publish_d1_reports": {
        "inputs": [
            {"namespace": SQLSERVER_NS, "name": "demopoc.dbo.ADWPM_MOVIMENTO_NEGOCIO_DERIVATIVO"},
            {"namespace": SQLSERVER_NS, "name": "demopoc.dbo.ADWPM_POSICAO_DERIVATIVO_NAO_FUNGIVEL"},
            {"namespace": SQLSERVER_NS, "name": "demopoc.dbo.ADWPM_POSICAO_MERCADO_A_VISTA"},
            {"namespace": SQLSERVER_NS, "name": "demopoc.dbo.ADWPM_DQ_RESULTS"},
        ],
        "outputs": [
            {"namespace": MINIO_NS, "name": "derivatives/ADWPM_MOVIMENTO_NEGOCIO_DERIVATIVO.parquet"},
            {"namespace": MINIO_NS, "name": "derivatives/ADWPM_POSICAO_DERIVATIVO_NAO_FUNGIVEL.parquet"},
            {"namespace": MINIO_NS, "name": "spot/ADWPM_POSICAO_MERCADO_A_VISTA.csv"},
        ],
    },
}
